name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Install uv
      uses: astral-sh/setup-uv@v4
      with:
        version: "latest"
    
    - name: Set up Python 3.12
      run: uv python install 3.12
    
    - name: Install dependencies
      run: uv sync
    
    - name: Format code
      run: make format
    
    - name: Lint with ruff
      run: uv run ruff check
    
    - name: Test CLI functionality
      run: make test
    
    - name: Build package
      run: make build